# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='model.proto',
  package='cnr.kdd.lore.tabular.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bmodel.proto\x12\x17\x63nr.kdd.lore.tabular.v1\"\x1e\n\rTupleInstance\x12\r\n\x05\x66ield\x18\x01 \x03(\x02\"6\n\x10TupleExplanation\x12\x0c\n\x04rule\x18\x01 \x01(\t\x12\x14\n\x0c\x63ounter_rule\x18\x02 \x01(\t2z\n\x14LoreTabularExplainer\x12\x62\n\rexplain_tuple\x12&.cnr.kdd.lore.tabular.v1.TupleInstance\x1a).cnr.kdd.lore.tabular.v1.TupleExplanationb\x06proto3'
)




_TUPLEINSTANCE = _descriptor.Descriptor(
  name='TupleInstance',
  full_name='cnr.kdd.lore.tabular.v1.TupleInstance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='field', full_name='cnr.kdd.lore.tabular.v1.TupleInstance.field', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=70,
)


_TUPLEEXPLANATION = _descriptor.Descriptor(
  name='TupleExplanation',
  full_name='cnr.kdd.lore.tabular.v1.TupleExplanation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rule', full_name='cnr.kdd.lore.tabular.v1.TupleExplanation.rule', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='counter_rule', full_name='cnr.kdd.lore.tabular.v1.TupleExplanation.counter_rule', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=126,
)

DESCRIPTOR.message_types_by_name['TupleInstance'] = _TUPLEINSTANCE
DESCRIPTOR.message_types_by_name['TupleExplanation'] = _TUPLEEXPLANATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TupleInstance = _reflection.GeneratedProtocolMessageType('TupleInstance', (_message.Message,), {
  'DESCRIPTOR' : _TUPLEINSTANCE,
  '__module__' : 'model_pb2'
  # @@protoc_insertion_point(class_scope:cnr.kdd.lore.tabular.v1.TupleInstance)
  })
_sym_db.RegisterMessage(TupleInstance)

TupleExplanation = _reflection.GeneratedProtocolMessageType('TupleExplanation', (_message.Message,), {
  'DESCRIPTOR' : _TUPLEEXPLANATION,
  '__module__' : 'model_pb2'
  # @@protoc_insertion_point(class_scope:cnr.kdd.lore.tabular.v1.TupleExplanation)
  })
_sym_db.RegisterMessage(TupleExplanation)



_LORETABULAREXPLAINER = _descriptor.ServiceDescriptor(
  name='LoreTabularExplainer',
  full_name='cnr.kdd.lore.tabular.v1.LoreTabularExplainer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=128,
  serialized_end=250,
  methods=[
  _descriptor.MethodDescriptor(
    name='explain_tuple',
    full_name='cnr.kdd.lore.tabular.v1.LoreTabularExplainer.explain_tuple',
    index=0,
    containing_service=None,
    input_type=_TUPLEINSTANCE,
    output_type=_TUPLEEXPLANATION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LORETABULAREXPLAINER)

DESCRIPTOR.services_by_name['LoreTabularExplainer'] = _LORETABULAREXPLAINER

# @@protoc_insertion_point(module_scope)
