# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import model_pb2 as model__pb2


class LoreTabularExplainerStub(object):
    """Service for explanation
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.explain_tuple = channel.unary_unary(
                '/cnr.kdd.lore.tabular.v1.LoreTabularExplainer/explain_tuple',
                request_serializer=model__pb2.TupleInstance.SerializeToString,
                response_deserializer=model__pb2.TupleExplanation.FromString,
                )


class LoreTabularExplainerServicer(object):
    """Service for explanation
    """

    def explain_tuple(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LoreTabularExplainerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'explain_tuple': grpc.unary_unary_rpc_method_handler(
                    servicer.explain_tuple,
                    request_deserializer=model__pb2.TupleInstance.FromString,
                    response_serializer=model__pb2.TupleExplanation.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cnr.kdd.lore.tabular.v1.LoreTabularExplainer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LoreTabularExplainer(object):
    """Service for explanation
    """

    @staticmethod
    def explain_tuple(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cnr.kdd.lore.tabular.v1.LoreTabularExplainer/explain_tuple',
            model__pb2.TupleInstance.SerializeToString,
            model__pb2.TupleExplanation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
